import os
import uuid
import json
import sqlite3
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[]
)

client = Groq(api_key=os.getenv("GROQ_API_KEY"))


def init_db():
    conn = sqlite3.connect("audit.db")
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS audit_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            content_id TEXT,
            creator_id TEXT,
            timestamp TEXT,
            attribution TEXT,
            confidence REAL,
            llm_score REAL,
            status TEXT,
            entry_type TEXT,
            appeal_reason TEXT
        )
    """)
    conn.commit()
    conn.close()


def write_log(entry):
    conn = sqlite3.connect("audit.db")
    c = conn.cursor()
    c.execute("""
        INSERT INTO audit_log 
        (content_id, creator_id, timestamp, attribution, confidence, llm_score, status, entry_type, appeal_reason)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        entry.get("content_id"),
        entry.get("creator_id"),
        entry.get("timestamp"),
        entry.get("attribution"),
        entry.get("confidence"),
        entry.get("llm_score"),
        entry.get("status"),
        entry.get("entry_type", "classification"),
        entry.get("appeal_reason")
    ))
    conn.commit()
    conn.close()


def get_log(limit=20):
    conn = sqlite3.connect("audit.db")
    c = conn.cursor()
    c.execute("SELECT * FROM audit_log ORDER BY id DESC LIMIT ?", (limit,))
    rows = c.fetchall()
    conn.close()
    keys = ["id", "content_id", "creator_id", "timestamp", "attribution",
            "confidence", "llm_score", "status", "entry_type", "appeal_reason"]
    return [dict(zip(keys, row)) for row in rows]


def get_llm_score(text):
    prompt = f"""You are an AI content classifier. Analyze the following text and determine whether it was written by a human or generated by AI.

Return ONLY a JSON object with two fields:
- "score": a float between 0.0 and 1.0 where 0.0 means definitely human and 1.0 means definitely AI
- "reason": one sentence explaining your assessment

Text to analyze:
{text}

Respond with only the JSON object, no other text."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1
    )

    raw = response.choices[0].message.content.strip()

    try:
        result = json.loads(raw)
        score = float(result["score"])
        score = max(0.0, min(1.0, score))
        return score, result.get("reason", "")
    except Exception:
        return 0.5, "Could not parse LLM response"


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute")
def submit():
    data = request.get_json()

    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "text and creator_id are required"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    llm_score, llm_reason = get_llm_score(text)

    confidence = llm_score

    if confidence >= 0.80:
        attribution = "likely_ai"
    elif confidence <= 0.35:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    label = "placeholder label"

    timestamp = datetime.now(timezone.utc).isoformat()

    write_log({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": round(confidence, 4),
        "llm_score": round(llm_score, 4),
        "status": "classified",
        "entry_type": "classification"
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": round(confidence, 4),
        "llm_score": round(llm_score, 4),
        "llm_reason": llm_reason,
        "label": label,
        "status": "classified"
    })


@app.route("/log", methods=["GET"])
def log():
    limit = request.args.get("limit", 20)
    entries = get_log(int(limit))
    return jsonify({"entries": entries})


if __name__ == "__main__":
    init_db()
    app.run(debug=True)